auth:
  type: config
  users:
    tester:
      password: test
      roles:
        - basic
    admin:
      password: admin
      roles:
        - admin

server:
  applicationConnectors:
      - type: http
        port: ${PORT:-9478}
  applicationContextPath: /
  adminContextPath: /admin
  adminConnectors:
      - type: http
        port: ${ADMIN_PORT:-8081}

logging:
  level: INFO
  appenders:
      - type: file
        currentLogFilename: /app/logs/rest-auth.log
        archive: true
        archivedLogFilenamePattern: /app/logs/rest-auth-%d-%i.log
        archivedFileCount: 5
        timeZone: UTC
        maxFileSize: 100MB
      - type: console
