auth:
  type: config
  users:
    tester:
      password: test
      roles:
        - basic
    admin:
      password: admin
      roles:
        - admin

server:
  applicationConnectors:
      - type: http
        port: 18181
  applicationContextPath: /
  adminContextPath: /admin
  adminConnectors:
      - type: http
        port: 18989

logging:
  level: INFO
  appenders:
      - type: file
        currentLogFilename: logs/rest-auth.log
        archive: true
        archivedLogFilenamePattern: logs/rest-auth-%d.log
        archivedFileCount: 9
        timeZone: UTC