version: 2
jobs:
  build:
    machine: true
    working_directory: ~/repo

    environment:
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
        
      # run tests!
      - run: ./gradlew test
      - deploy:
          name: "Build & Deploy Docker Image"
          command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                  echo "Build Docker Image"
                  ./gradlew dockerTagLatest
                  echo "Push Docker Image"
                  ./gradlew dockerPushLatest
              fi