version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8
    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
        
      - run: ./gradlew build --no-daemon
      - deploy:
          name: "Build & Deploy Docker Image"
          command: |
              export PATH=~/.local/bin:$PATH
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                  echo "Build and Push Docker Image"
                  ./gradlew dockerPushLatest
              fi